all: True
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase }}_mock.go"
structname: "{{.InterfaceName | firstUpper}}"
recursive: True
pkgname: "mock{{.SrcPackageName | camelcase | firstUpper }}"
template: testify
packages:
  newsapi/internal/domain/newsAgr:
  newsapi/internal/controller/http2/middleware:
  newsapi/internal/controller/http2/register_handler:
