#volumes:
#  npc.pgsql.data:

networks:
  proxy:
   external: true
  npc.network:
#    external: true

services:
  dsaime.test.newsapi:
    container_name: dsaime.test.newsapi
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      dsaime.test.mysql:
        condition: service_healthy
    command:
      - "--http-addr"
      - ":8080"
      - "--mysql-dsn"
      - "root:root@tcp(dsaime.test.mysql:3306)/test_db"
      - "--log-level"
      - "debug"

# https://hub.docker.com/_/mysql
  dsaime.test.mysql:
    container_name: dsaime.test.mysql
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d


