// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockNewsAgr

import (
	"newsapi/internal/domain/newsAgr"

	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type Repository
func (_mock *Repository) Find(filter newsAgr.Filter) (newsAgr.News, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 newsAgr.News
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(newsAgr.Filter) (newsAgr.News, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(newsAgr.Filter) newsAgr.News); ok {
		r0 = returnFunc(filter)
	} else {
		r0 = ret.Get(0).(newsAgr.News)
	}
	if returnFunc, ok := ret.Get(1).(func(newsAgr.Filter) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Repository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - filter newsAgr.Filter
func (_e *Repository_Expecter) Find(filter interface{}) *Repository_Find_Call {
	return &Repository_Find_Call{Call: _e.mock.On("Find", filter)}
}

func (_c *Repository_Find_Call) Run(run func(filter newsAgr.Filter)) *Repository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 newsAgr.Filter
		if args[0] != nil {
			arg0 = args[0].(newsAgr.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_Find_Call) Return(news newsAgr.News, err error) *Repository_Find_Call {
	_c.Call.Return(news, err)
	return _c
}

func (_c *Repository_Find_Call) RunAndReturn(run func(filter newsAgr.Filter) (newsAgr.News, error)) *Repository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// InTransaction provides a mock function for the type Repository
func (_mock *Repository) InTransaction(fn func(txRepo newsAgr.Repository) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for InTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(txRepo newsAgr.Repository) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_InTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InTransaction'
type Repository_InTransaction_Call struct {
	*mock.Call
}

// InTransaction is a helper method to define mock.On call
//   - fn func(txRepo newsAgr.Repository) error
func (_e *Repository_Expecter) InTransaction(fn interface{}) *Repository_InTransaction_Call {
	return &Repository_InTransaction_Call{Call: _e.mock.On("InTransaction", fn)}
}

func (_c *Repository_InTransaction_Call) Run(run func(fn func(txRepo newsAgr.Repository) error)) *Repository_InTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(txRepo newsAgr.Repository) error
		if args[0] != nil {
			arg0 = args[0].(func(txRepo newsAgr.Repository) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_InTransaction_Call) Return(err error) *Repository_InTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_InTransaction_Call) RunAndReturn(run func(fn func(txRepo newsAgr.Repository) error) error) *Repository_InTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(filter newsAgr.Filter) ([]newsAgr.News, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []newsAgr.News
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(newsAgr.Filter) ([]newsAgr.News, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(newsAgr.Filter) []newsAgr.News); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]newsAgr.News)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(newsAgr.Filter) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filter newsAgr.Filter
func (_e *Repository_Expecter) List(filter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", filter)}
}

func (_c *Repository_List_Call) Run(run func(filter newsAgr.Filter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 newsAgr.Filter
		if args[0] != nil {
			arg0 = args[0].(newsAgr.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(newss []newsAgr.News, err error) *Repository_List_Call {
	_c.Call.Return(newss, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(filter newsAgr.Filter) ([]newsAgr.News, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type Repository
func (_mock *Repository) Upsert(news newsAgr.News) (int, error) {
	ret := _mock.Called(news)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(newsAgr.News) (int, error)); ok {
		return returnFunc(news)
	}
	if returnFunc, ok := ret.Get(0).(func(newsAgr.News) int); ok {
		r0 = returnFunc(news)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(newsAgr.News) error); ok {
		r1 = returnFunc(news)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Repository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - news newsAgr.News
func (_e *Repository_Expecter) Upsert(news interface{}) *Repository_Upsert_Call {
	return &Repository_Upsert_Call{Call: _e.mock.On("Upsert", news)}
}

func (_c *Repository_Upsert_Call) Run(run func(news newsAgr.News)) *Repository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 newsAgr.News
		if args[0] != nil {
			arg0 = args[0].(newsAgr.News)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_Upsert_Call) Return(id int, err error) *Repository_Upsert_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *Repository_Upsert_Call) RunAndReturn(run func(news newsAgr.News) (int, error)) *Repository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
