// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"newsapi/internal/usecases/news/news_list"

	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForNewsList creates a new instance of UsecasesForNewsList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForNewsList(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForNewsList {
	mock := &UsecasesForNewsList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForNewsList is an autogenerated mock type for the UsecasesForNewsList type
type UsecasesForNewsList struct {
	mock.Mock
}

type UsecasesForNewsList_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForNewsList) EXPECT() *UsecasesForNewsList_Expecter {
	return &UsecasesForNewsList_Expecter{mock: &_m.Mock}
}

// NewsList provides a mock function for the type UsecasesForNewsList
func (_mock *UsecasesForNewsList) NewsList(in newsList.In) (newsList.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for NewsList")
	}

	var r0 newsList.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(newsList.In) (newsList.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(newsList.In) newsList.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(newsList.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(newsList.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForNewsList_NewsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewsList'
type UsecasesForNewsList_NewsList_Call struct {
	*mock.Call
}

// NewsList is a helper method to define mock.On call
//   - in newsList.In
func (_e *UsecasesForNewsList_Expecter) NewsList(in interface{}) *UsecasesForNewsList_NewsList_Call {
	return &UsecasesForNewsList_NewsList_Call{Call: _e.mock.On("NewsList", in)}
}

func (_c *UsecasesForNewsList_NewsList_Call) Run(run func(in newsList.In)) *UsecasesForNewsList_NewsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 newsList.In
		if args[0] != nil {
			arg0 = args[0].(newsList.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForNewsList_NewsList_Call) Return(out newsList.Out, err error) *UsecasesForNewsList_NewsList_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForNewsList_NewsList_Call) RunAndReturn(run func(in newsList.In) (newsList.Out, error)) *UsecasesForNewsList_NewsList_Call {
	_c.Call.Return(run)
	return _c
}
